name: Functional Testing

on:
  push:
    branches: [ "main", "juan_felipe/dev" ]
  pull_request:
    branches: [ "main", "juan_felipe/dev" ]

jobs:
  install-and-tests:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    environment: Preview
    permissions:
      contents: read
      security-events: write


    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      CACHE_TTL: ${{ secrets.CACHE_TTL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME }}
      NEXT_PUBLIC_MAPBOX_API_KEY: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        working-directory: hospitapp
        run: npm install

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: 135.0.7049.84
          install-chromedriver: true

      - name: Verify Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Cucumber Tests
        working-directory: hospitapp
        run: npm run test:local

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            hospitapp/**/*.png
            hospitapp/**/*.log
            hospitapp/cucumber-report.html
