name: Functional Testing

on:
  push:
    branches: ["main", "juan_felipe/dev"]
  pull_request:
    branches: ["main", "juan_felipe/dev"]

jobs:
  install-and-tests:
    name: Run Functional Tests
    runs-on: ubuntu-latest
    environment: Preview
    permissions:
      contents: read
      security-events: write
      issues: write # Required for creating issues

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      CACHE_TTL: ${{ secrets.CACHE_TTL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME }}
      NEXT_PUBLIC_MAPBOX_API_KEY: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        working-directory: hospitapp
        run: npm install

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: 135.0.7049.84
          install-chromedriver: true

      - name: Verify Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Cucumber Tests
        working-directory: hospitapp
        run: npm run test:local

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            hospitapp/**/*.png
            hospitapp/**/*.log
            hospitapp/cucumber-report.html

      - name: Create GitHub Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read cucumber-report.html
            const reportPath = 'hospitapp/cucumber-report.html';
            let reportContent = '';
            try {
              reportContent = fs.readFileSync(reportPath, 'utf8');
            } catch (error) {
              console.error('Failed to read cucumber-report.html:', error);
              return;
            }
            
            // Create issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Functional Test Failure - Run #${context.runId}`,
              body: `
                Functional tests failed in workflow run #${context.runId}.
                
                **Details:**
                - Workflow: ${context.workflow}
                - Run ID: ${context.runId}
                - Commit: ${context.sha}
                - Branch: ${context.ref}
                
                The test report (cucumber-report.html) is attached as an artifact in the workflow run:
                [View Artifacts](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
                
                **Test Output:**
                \`\`\`
                ${process.env.TEST_OUTPUT || 'No test output captured'}
                \`\`\`
              `,
              labels: ['bug', 'test-failure'],
              assignees: ['JuanFelipeRestrepoBuitrago'] // Replace with your GitHub username or team
            });
            
            console.log(`Created issue #${issue.data.number}`);