name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        working-directory: hospitapp
        run: npm install

      - name: Run ESLint
        working-directory: hospitapp
        run: npm run lint